imports:
  - php

filter:
  excluded_paths:
    - 'bin/*'
    - 'vendor/*'
    - 'features/*'
    - 'spec/*'

before_commands:
  - composer install --prefer-source --dev --optimize-autoloader --no-interaction
    
tools:
  php_sim: true
  php_cpd: false

  # PHP Code Sniffer
  php_code_sniffer:
    config:
      standard: PSR2