language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpenv config-add .travis.php.ini; fi;'
  - if [[ "$TRAVIS_PHP_VERSION" == hhvm* ]]; then echo -e '\nhhvm.libxml.ext_entity_whitelist = "file"\n  - if [[ "$TRAVIS_PHP_VERSION" == hhvm* ]]; then echo -e '\nhhvm.libxml.ext_entity_whitelist = "file"\ndate.timezone = "UTC"' | sudo tee -a /etc/hhvm/php.ini; fi' | sudo tee -a /etc/hhvm/php.ini; fi
  - travis_retry pecl install SPL_Types
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction --optimize-autoloader

script:
  - ./vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml
#  - ./vendor/bin/phpcs --standard=PSR2 ./src/ ./tests/

matrix:
  fast_finish: true
