language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_script:
  - pecl install SPL_Types
  - echo 'date.timezone = "UTC"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer selfupdate
  - composer install --prefer-source

script:
  - find src -name "*.php" | xargs -n1 php -l
  - bin/phpspec run --no-interaction --format=pretty
  - bin/behat --format=pretty
